name: build on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ["suning/fruits"]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: build
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: clone
        working-directory: ./dist
        run: |
          git clone https://github.com/demoshang/Auto.js.git
          ls -la ./

      - name: ${{ matrix.project }} run autojs-replace-inrt
        working-directory: ./dist
        run: |
          cd ./Auto.js && git add -A && git checkout -f && cd ..
          npx @s4p/autojs-replace-inrt "./Auto.js" "./${{ matrix.project }}"
          cd "./Auto.js"
          git status

      - name: ${{ matrix.project }} run Build with Gradle
        working-directory: ./dist/Auto.js
        run: chmod 777 ./gradlew && ./gradlew :inrt:assembleDebug && find inrt/build/outputs

      - name: ${{ matrix.project }} run Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: debug-app
          path: dist/Auto.js/inrt/build/outputs/apk/debug/
